### ISSUE TITLE
Custom delimiter for messages

### ISSUE THREAD

**Issue by joao-v-maia** [Leviosar/steganossaurus#5]
Currently, we only support a default delimiter `"#####"`, it's a good idea to support this as an optional parameter, both in decode and encode commands.

For example, the user wants to encode the text "michael, michael, eles não ligam para nós" inside `michael.png` image, by default the encoded text is actually "michael, michael, eles não ligam para nós#####", and we use the `#####` during the decoding process to find the message's end.

But what if a user wants to encode a .md file, in Markdown "#####" could be used to create a headtitle, the encode process would work fine, but during decode the program would stop at the first delimiter found, loosing the rest of the message. In this case, a custom delimiter is necessary to properly encode/decode the message.

Custom delimiters should be passed as a CLI option and used by the handlers.

**Comment by shawalli** [comment]
I'd like to add this feature. Would you mind assigning to me? Thanks!

**Comment by joao-v-maia** [comment]
Assigned, go for it!
